swagger: "2.0"
info:
  version: "0.0.1"
  title: Ola Queuing System API
# during dev, should point to your local machine
host: localhost:8080
# basePath prefixes all resource paths
basePath: /api/v0
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
