parameters:
  # Meta parameters
  driverId:
    name: driverId
    in: header
    type: string
    description: Driver id
  status:
    name: status
    in: query
    type: string
    enum:
      - waiting
      - ongoing
      - completed
    description: Trip/Request status
  # Pagination parameters
  page:
    name: page
    in: query
    type: integer
    description: Page number of the results
    minimum: 1
    default: 1
  size:
    name: size
    in: query
    type: integer
    description: Number of documents to be returned per page
    minimum: 1
    maximum: 1000
    default: 10
